name: flutter_core
description: Core module for Flutter-based shared functionality.

# The version of the project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies for the project.
dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  provider: ^6.0.5
  shared_preferences: ^2.1.2
  dio: ^5.1.2
  json_serializable: ^6.7.0
  connectivity_plus: ^6.1.0
  intl: ^0.19.0
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  logger: ^2.5.0
  url_launcher: ^6.1.10

  # Additional dependencies that might be required.
  path_provider: ^2.1.3
  device_info_plus: ^11.1.1
  package_info_plus: ^8.1.1
  flutter_localizations:
    sdk: flutter

# Development dependencies for tooling.
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mockito: ^5.4.2
  lint: ^2.1.1

flutter:
  uses-material-design: true

  # Assets configuration.
  assets:
    - assets/images/
    - assets/icons/

  # Fonts configuration.
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
